### ISSUE TITLE
Type coercion does not work during interaction verification

### ISSUE THREAD

**Issue by monrealis** [spockframework/spock#1260]
```groovy
import java.util.function.Consumer

import spock.lang.Specification

class MySpec extends Specification {
    def "type coercion does not work during interaction verification"() {
        given:
        Consumer good1 = Mock(Consumer)
        Consumer good2 = Mock(Consumer)
        Consumer good3 = Mock(Consumer)
        Consumer good4 = Mock(Consumer)
        Consumer bad = Mock(Consumer)

        when:
        good1.accept([])
        good2.accept([] as Set)
        good3.accept([] as Set)
        good4.accept([] as Set)
        bad.accept([] as Set)

        then:
        1 * good1.accept([])
        1 * good2.accept(new HashSet([]))
        1 * good3.accept(new LinkedHashSet([]))
        1 * good4.accept({it == [] as Set})
        1 * bad.accept([] as Set)
    }
}
```
results in failure

```
Too few invocations for:

1 * bad.accept([] as Set)   (0 invocations)

Unmatched invocations (ordered by similarity):

1 * bad.accept([])
One or more arguments(s) didn't match:
0: argument == expected
   |        |  |
   |        |  [] (java.util.ArrayList)
   |        false
   [] (java.util.LinkedHashSet)


	at org.spockframework.mock.runtime.InteractionScope.verifyInteractions(InteractionScope.java:98)
	at org.spockframework.mock.runtime.MockController.leaveScope(MockController.java:77)
	at MySpec.type coercion does not work during interaction verification(MySpec.groovy:19)
```

Spock version: 1.3-groovy-2.5.

**Comment by Vampire** [comment]
Can you try with 2.0?
I fixed similar things, so with 2.0 this might already work as expected.

**Comment by monrealis** [comment]
The issue still remains in the newest version  that I can find in https://mvnrepository.com - 2.0-M3-groovy-2.5.

```
Too few invocations for:

1 * bad.accept([] as Set)   (0 invocations)

Unmatched invocations (ordered by similarity):

1 * bad.accept([])
One or more arguments(s) didn't match:
0: argument == expected
   |        |  |
   |        |  [] (java.util.ArrayList)
   |        false
   [] (java.util.LinkedHashSet)


	at org.spockframework.mock.runtime.InteractionScope.verifyInteractions(InteractionScope.java:104)
	at org.spockframework.mock.runtime.MockController.leaveScope(MockController.java:77)
	at MySpec.type coercion does not work during interaction verification(MySpec.groovy:19)
```

**Comment by szpak** [comment]
Hmm, you seemed to miss 2.0-M4:
![image](https://user-images.githubusercontent.com/148013/104784046-b42d4800-5787-11eb-9ebe-1423e9e39f06.png)
(I don't remember which version contains @Vampire fixes)

**Comment by monrealis** [comment]
Not yet fixed in 2.0-M4-groovy-3.0:

```spock
Too few invocations for:

1 * bad.accept([] as Set)   (0 invocations)

Unmatched invocations (ordered by similarity):

1 * bad.accept([])
One or more arguments(s) didn't match:
0: argument == expected
   |        |  |
   |        |  [] (java.util.ArrayList)
   |        false
   [] (java.util.LinkedHashSet)


	at org.spockframework.mock.runtime.InteractionScope.verifyInteractions(InteractionScope.java:104)
	at org.spockframework.mock.runtime.MockController.leaveScope(MockController.java:77)
	at MySpec.type coercion does not work during interaction verification(MySpec.groovy:19)
```

**Comment by szpak** [comment]
Thanks for checking.

Btw, not related with your question, but get know that some time ago I improved the mock creation syntax and currently you can just write:
> Consumer good1 = Mock()

instead of:
> Consumer good1 = Mock(Consumer)

and still doesn't have a warning in Idea.

**Comment by monrealis** [comment]
> Thanks for checking.
> 
> Btw, not related with your question, but get know that some time ago I improved the mock creation syntax and currently you can just write:
> 
> > Consumer good1 = Mock()
> 
> instead of:
> 
> > Consumer good1 = Mock(Consumer)
> 
> and still doesn't have a warning in Idea.



> Thanks for checking.
> 
> Btw, not related with your question, but get know that some time ago I improved the mock creation syntax and currently you can just write:
> 
> > Consumer good1 = Mock()
> 
> instead of:
> 
> > Consumer good1 = Mock(Consumer)
> 
> and still doesn't have a warning in Idea.

Thanks, will try to use it with 1.3, the version in my project! I use Eclipse, by the way.

**Comment by monrealis** [comment]
Just interested, since which version did you improve mock creation syntax? I don't see warnings in Eclipse in 1.2, 1.3, 2.0.

**Comment by leonard84** [comment]
This is a corner case of the [argument matcher](http://spockframework.org/spock/docs/1.3/all_in_one.html#_argument_constraints) API.

Normally you'd write something like this:
`1 * subscriber.receive(_ as String)    // any non-null argument that is-a String`
or in your case it would be `1 * bad.accept(_ as Set)`.

Spock transforms `1 * bad.accept([] as Set)` into two distinct constraints: `.addEqualArg([]).typeLastArg(java.util.Set)` i.e. checking the type to be `Set` and testing it to be the same as the `ArrayList`, which fails of course.

**Comment by szpak** [comment]
> Just interested, since which version did you improve mock creation syntax? I don't see warnings in Eclipse with 1.2, 1.3, 2.0.

I've check it, and the [commit](https://github.com/spockframework/spock/commit/8e0590c74c47ec66b4bb67858d06569668b916d0) was made over 5 years ago. Spock 1.1+.

**Comment by leonard84** [comment]
I've created a potential fix for this special case, but there will still be many other cases where this won't apply. 
So, should we create the special handling for the `ListExpression` or just keep it as it is for consistency?

WDYT @spockframework/supporter  ?

**Comment by mkutz** [comment]
Is this not a general issue with generic types?

Generally I think adding the special case is a good idea as collections are an extremely common use case.
