### ISSUE TITLE
IllegalArgumentException when mocking java.io.PrintStream

### ISSUE THREAD

**Issue by robfletcher** [spockframework/spock#506]
Originally reported on Google Code with ID 384
```
When I attempt to run a spec that mocks java.io.PrintStream I get an IllegalArgumentException
thrown:

class PrintSpec extends Specification {
    private PrintStream printStream = Mock()
}

spock-core version - 0.7-groovy-2.0
cglib-nodep version - 3.1
objenesis version - 2.1
groovy-all version - 2.3.9

Here is the stacktrace:
java.lang.IllegalArgumentException
	at net.sf.cglib.proxy.BridgeMethodResolver.resolveAll(BridgeMethodResolver.java:61)
	at net.sf.cglib.proxy.Enhancer.emitMethods(Enhancer.java:911)
	at net.sf.cglib.proxy.Enhancer.generateClass(Enhancer.java:498)
	at net.sf.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:216)
	at net.sf.cglib.proxy.Enhancer.createHelper(Enhancer.java:377)
	at net.sf.cglib.proxy.Enhancer.createClass(Enhancer.java:317)
	at org.spockframework.mock.runtime.ProxyBasedMockFactory$CglibMockFactory.createMock(ProxyBasedMockFactory.java:91)
	at org.spockframework.mock.runtime.ProxyBasedMockFactory.create(ProxyBasedMockFactory.java:49)
	at org.spockframework.mock.runtime.JavaMockFactory.create(JavaMockFactory.java:51)
	at org.spockframework.mock.runtime.CompositeMockFactory.create(CompositeMockFactory.java:44)
	at org.spockframework.lang.SpecInternals.createMock(SpecInternals.java:47)
	at org.spockframework.lang.SpecInternals.createMockImpl(SpecInternals.java:282)
	at org.spockframework.lang.SpecInternals.MockImpl(SpecInternals.java:83)

```

Reported by `jameslorenzen` on 2015-01-21 05:38:49

**Comment by leonard84** [comment]
This works in the current master and should be fixed with release 1.1

**Comment by mtadmk** [comment]
It is still occurring to me. Env:
'org.spockframework', name: 'spock-core', version: '1.1-groovy-2.4-rc-2'
windows 10 x64
java 1.8.0_91 x64

the same with version 1.0
